// ============================================================================
// GridGuard data model — generated by agent/generate_scenarios.py
//   Physics: pandapower ring feeder (IEEE 123-node equivalent)
//   AI:      DeepSeek LLM corrective control loop
// ============================================================================

import s1 from "./agent-data/n1-line13.json";
import s2 from "./agent-data/n1-line19.json";
import s3 from "./agent-data/n1-line55.json";

export type Risk = "Low" | "Medium" | "High";
export type Severity = "Critical" | "Warning" | "Elevated";
export type ActionType =
  | "redispatch_up"
  | "redispatch_down"
  | "curtail_load"
  | "discharge_battery"
  | "charge_battery"
  | "curtail_renewable";

export const ACTION_LABEL: Record<ActionType, string> = {
  redispatch_up: "Redispatch ↑",
  redispatch_down: "Redispatch ↓",
  curtail_load: "Curtail Load",
  discharge_battery: "BESS Discharge",
  charge_battery: "BESS Charge",
  curtail_renewable: "Curtail Renewable",
};

export interface ScreeningRow {
  lineIndex: number;
  name: string;
  converged: boolean;
  nOverloaded: number;
  maxLoadingPct: number;
  riskScore: number;
  islandKw?: number;
}

export interface ActionOption {
  targetId: string;
  bus: string;
  label: string;
  actionType: ActionType;
  maxAvailableMw: number;
  costPerMw: number;
  sensitivity: number;
  targetLine: string;
  socPct?: number;
  recommended?: boolean;
}

export interface AppliedAction {
  targetId: string;
  bus: string;
  label: string;
  actionType: ActionType;
  amountMw: number;
  costPerMw: number;
}

export interface CorrectiveIteration {
  iteration: number;
  reasoning: string;
  actions: AppliedAction[];
  maxLoadingBefore: number;
  maxLoadingAfter: number;
  overloadsBefore: number;
  overloadsAfter: number;
  undervoltBefore: number;
  undervoltAfter: number;
  costEur: number;
}

export interface OverloadedLine {
  lineIndex: number;
  name: string;
  from: string;
  to: string;
  loading: number;
}

export interface ForecastHour {
  hour: number;
  condition: string;
  tempC: number;
  windMs: number;
  solarMw: number;
  windMw: number;
  loadMw: number;
  dayAheadPrice: number;
  balancingPrice: number;
}

export interface BessUnit {
  id: string;
  bus: string;
  powerMw: number;
  energyMwh: number;
  socPct: number;
}

export interface AssetHealth {
  derated: { line: string; healthPct: number; deratePct: number }[];
  maintenance: string;
}

export interface BaselineCompare {
  llm: { secure: boolean; costEur: number; actions: number };
  lp:  { secure: boolean; costEur: number; actions: number };
}

export interface Scenario {
  id: string;
  name: string;
  network: string;
  issue: string;
  severity: Severity;
  faultLine: { index: number; name: string; from: string; to: string };
  weather: { profile: string; hour: number; forecast: ForecastHour[] };
  bess: BessUnit[];
  assetHealth: AssetHealth;
  screeningSummary: { total: number; catastrophic: number; dangerous: number; safe: number; islanding: number };
  screening: ScreeningRow[];
  postFault: { maxLoading: number; undervoltBuses: number; overloaded: OverloadedLine[] };
  actionSpace: ActionOption[];
  iterations: CorrectiveIteration[];
  baseline: BaselineCompare;
  totalCost: number;
  finalMaxLoading: number;
}

export const SCENARIOS: Scenario[] = [s1, s2, s3] as unknown as Scenario[];

export const KPIS = {
  network: "GridGuard ring feeder",
  buses: 15,
  activeLines: 15,
  derAssets: 8,
  peakLoad: "6.0 MW",
};
